language: generic

sudo: required

services:
    - docker

script:
    - docker run --rm --privileged multiarch/qemu-user-static:register
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh ${DOCKER_IMAGE#*/}

env:
    - DOCKER_IMAGE=centos:7
    - DOCKER_IMAGE=fedora:28
    - DOCKER_IMAGE=fedora:27
    - DOCKER_IMAGE=fedora:26
    - DOCKER_IMAGE=multiarch/fedora:25-armhfp
    - DOCKER_IMAGE=multiarch/fedora:25-aarch64
    - DOCKER_IMAGE=multiarch/centos:7-armhfp-iso
    - DOCKER_IMAGE=multiarch/centos:7-aarch-iso
    - DOCKER_IMAGE=muttiarch/centos:7-i386-iso

matrix:
    allow_failures:
        - env: DOCKER_IMAGE=multiarch/fedora:25-armhfp
        - env: DOCKER_IMAGE=multiarch/fedora:25-aarch64
        - env: DOCKER_IMAGE=multiarch/centos:7-armhfp-iso
        - env: DOCKER_IMAGE=multiarch/centos:7-aarch-iso
        - env: DOCKER_IMAGE=muttiarch/centos:7-i386-iso

before_deploy:
    - openssl aes-256-cbc -K $encrypted_9241d2ed5547_key -iv $encrypted_9241d2ed5547_iv -in .copr.enc -out .copr -d

deploy:
    skip_cleanup: true
    provider: script
    script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --nowait simc/stable fedora/SPECS/wreport.spec"

    on:
        branch: master
        condition: $DOCKER_IMAGE = centos:7
