language: generic

sudo: required

services:
    - docker

script:
    - wget -P centos-armhfp-7 https://github.com/multiarch/qemu-user-static/releases/download/v2.7.0/x86_64_qemu-arm-static.tar.gz
    - docker build -t centos-armhfp:7 centos-armhfp-7
    - docker run --rm --privileged multiarch/qemu-user-static:register
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh ${DOCKER_IMAGE#*/}

env:
    - DOCKER_IMAGE=centos-armhfp:7

before_deploy:
    - openssl aes-256-cbc -K $encrypted_9241d2ed5547_key -iv $encrypted_9241d2ed5547_iv -in .copr.enc -out .copr -d

deploy:
    skip_cleanup: true
    provider: script
    script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --nowait simc/stable fedora/SPECS/wreport.spec"

    on:
        branch: master
        condition: $DOCKER_IMAGE = centos:7
